# Generated by Django 4.1.7 on 2023-08-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slide", models.ImageField(upload_to="")),
            ],
        ),
    ]
