# Generated by Django 4.1.7 on 2023-08-27 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_cartproduct_session_key_alter_cartproduct_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartproduct",
            name="session_key",
        ),
    ]
